version: '2'

services:
  whitelabel-super-backend-frontend:
    container_name: whitelabel-super-backend-frontend
    image: whitelabel-super-backend-frontend:0.0.1
    build: .
    volumes:
    - ./frontend:/app/frontend
    ports:
      - 2111:2111
    restart: always